package ReverseModule;


/**
* ReverseModule/Reverse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Friday, April 11, 2025 8:19:11 AM UTC
*/

public interface Reverse extends ReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reverse
