package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Friday, April 11, 2025 8:19:11 AM UTC
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
